### PR TITLE
Create INELT__Monolith_E1000LT-12V__nutdrv-qx__2.7.4__01.dev

### PR DESCRIPTION
**Pull request by RangerPCW**

### CODE REVIEW

**Comment by zykh** [comment]
Thanks, @RangerPCW -- could you also add the info from `upscmd` and `upsrw`, please?

Also, for the commit message, we usually use a format like this: "Add \<manufacturer> \<model> @ \<NUT version>", e.g., for this device, it should ideally be something like "Add INELT Monolith E1000LT-12V @ 2.7.4".

**Comment by zykh** [comment]
(I'm half asleep, and didn't notice this before)
For future reference, this is the same as https://alioth-lists.debian.net/pipermail/nut-upsuser/2019-March/011341.html

**Comment by RangerPCW** [comment]
> Thanks, @RangerPCW -- could you also add the info from `upscmd` and `upsrw`, please?
Yes, I can upload these files March 25-26.

**Comment by RangerPCW** [comment]
# upscmd -l inelt-boiler
Instant commands supported on UPS [inelt-boiler]:

beeper.disable - Disable the UPS beeper
beeper.enable - Enable the UPS beeper
beeper.toggle - Toggle the UPS beeper
bypass.start - Put the UPS in bypass mode
bypass.stop - Take the UPS out of bypass mode
load.off - Turn off the load immediately
load.on - Turn on the load immediately
shutdown.return - Turn off the load and return when power is back
shutdown.stayoff - Turn off the load and remain off
shutdown.stop - Stop a shutdown in progress
test.battery.start - Start a battery test
test.battery.start.deep - Start a deep battery test
test.battery.start.quick - Start a quick battery test
test.battery.stop - Stop the battery test

**Comment by RangerPCW** [comment]
# upsrw inelt-boiler
[battery.energysave]
Switch off when running on battery and no/low load
Type: ENUM
Option: "no" SELECTED
Option: "yes"

[battery.packs]
Number of battery packs
Type: RANGE
Option: "1-99" SELECTED

[battery.protection]
Prevent deep discharge of battery
Type: ENUM
Option: "no"
Option: "yes" SELECTED

[input.frequency.high]
Maximum input line frequency (Hz)
Type: RANGE
Option: "53-60" SELECTED

[input.frequency.low]
Minimum input line frequency (Hz)
Type: RANGE
Option: "40-47" SELECTED

[input.transfer.high]
High voltage transfer point (V)
Type: RANGE
Option: "237-254" SELECTED

[input.transfer.low]
Low voltage transfer point (V)
Type: RANGE
Option: "206-223" SELECTED

[ups.delay.shutdown]
Interval to wait after shutdown with delay command (seconds)
Type: RANGE
Option: "12-5940" SELECTED

[ups.delay.start]
Interval to wait before (re)starting the load (seconds)
Type: RANGE
Option: "0-599940" SELECTED

[ups.start.auto]
UPS starts when mains is (re)applied
Type: ENUM
Option: "no"
Option: "yes" SELECTED

[ups.start.battery]
Allow to start UPS from battery
Type: ENUM
Option: "no"
Option: "yes" SELECTED

**Pull request closed without merging**
